version: '3.3'
volumes:
  pg_data:
  media:
  static:
services:
  db:
    container_name: PAY2YOU_postgres_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    container_name: PAY2YOU_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file: .env

  backend:
    container_name: PAY2YOU_backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/app/media/
      - static:/app/static/

  celery_beat:
    container_name: PAY2YOU_celery_beat
    build: ./backend
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/usr/src/app
    env_file: .env
    depends_on:
      - backend
      - redis

  celery_worker:
    container_name: PAY2YOU_celery_worker
    build: ./backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/usr/src/app
    env_file: .env
    depends_on:
      - backend
      - redis

  nginx:
    container_name: PAY2YOU_nginx
    image: nginx:1.22.1
    ports:
      - 8000:80
    depends_on:
     - backend
    volumes:
      - media:/app/media/
      - static:/app/static/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
