version: '3'
volumes:
  pg_data:
  media:
  static:
services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    env_file: .env

  backend:
    image: euggross/pay2you_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - media:/app/media/
      - static:/backend_static/

  celery_beat:
    image: euggross/pay2you_backend
    command: celery -A backend beat --loglevel=info
    volumes:
      - ./backend:/usr/src/app
    env_file: .env
    depends_on:
      - backend
      - celery_worker
      - redis

  celery_worker:
    image: euggross/pay2you_backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/usr/src/app
    env_file: .env
    depends_on:
      - backend
      - redis

  nginx:
    image: euggross/pay2you_nginx
    ports:
      - 8000:80
    depends_on:
     - backend
    volumes:
      - media:/media/
      - static:/static/
