# Generated by Django 3.2.15 on 2024-03-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffcondition',
            name='tarrif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_condition', to='services.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='tariffspecialcondition',
            name='tariff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_special_conditions', to='services.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='tarifftrialperiod',
            name='tarrif',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_trial_period', to='services.tariff', verbose_name='Тариф'),
        ),
    ]
