# Generated by Django 3.2.15 on 2024-03-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240322_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='price',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Цена пробного периода'),
            preserve_default=False,
        ),
    ]
