# Generated by Django 3.2.15 on 2024-03-23 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240323_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffspecialcondition',
            name='tariff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_special_condition', to='services.tariff', verbose_name='Тариф'),
        ),
    ]
