# Generated by Django 3.2.15 on 2024-03-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_tariff_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TarrifCondition',
            new_name='TariffCondition',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Цена пробного периода'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='trial_period',
            field=models.CharField(blank=True, choices=[('D', 'Дней'), ('M', 'Месяцев'), ('Y', 'Год')], max_length=250, verbose_name='Пробный период (день, месяц, год)'),
        ),
    ]
