# Generated by Django 3.2.15 on 2024-03-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_tariffspecialcondition_tariff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffcondition',
            old_name='tarrif',
            new_name='tariff',
        ),
        migrations.RenameField(
            model_name='tarifftrialperiod',
            old_name='tarrif',
            new_name='tariff',
        ),
    ]
