# Generated by Django 3.2.15 on 2024-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20240325_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategoryimage',
            name='title',
            field=models.CharField(default=1, max_length=250, verbose_name='Заголовок к изображению'),
            preserve_default=False,
        ),
    ]
