# Generated by Django 3.2.15 on 2024-03-22 10:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'номер телефона пользователя',
                'verbose_name_plural': 'Номера телефона пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала подписки на сервис')),
                ('end_date', models.DateField(verbose_name='Дата окончания подписки на сервис')),
                ('is_active', models.PositiveSmallIntegerField(verbose_name='Активность подписки')),
                ('auto_pay', models.BooleanField(default=True, verbose_name='Автоплатеж')),
                ('phone_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to='users.userphonenumber', verbose_name='Номер телефона')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_services', to='services.service', verbose_name='Сервис')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_services', to='services.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'подписка пользователя',
                'verbose_name_plural': 'Подписки пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Сумма')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to='services.service', verbose_name='Сервис')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to='services.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'расходы пользователя',
                'verbose_name_plural': 'Расходы пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserCashback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Сумма')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cashback', to='services.service', verbose_name='Сервис')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cashback', to='services.tariff', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cashback', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'доходы пользователя',
                'verbose_name_plural': 'Доходы пользователя',
            },
        ),
        migrations.CreateModel(
            name='TrialPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата завершения')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_period', to='services.service', verbose_name='Сервис')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_period', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'пробный период',
                'verbose_name_plural': 'Пробный период',
            },
        ),
        migrations.AddConstraint(
            model_name='trialperiod',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='unique_user_service'),
        ),
    ]
