# Generated by Django 3.2.15 on 2024-03-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240323_2312'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_services', to='services.service', verbose_name='Сервис'),
            preserve_default=False,
        ),
    ]
