# Generated by Django 3.2.15 on 2024-03-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to='users.userphonenumber', verbose_name='Номер телефона'),
        ),
    ]
