# Generated by Django 3.2.15 on 2024-03-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='cashback',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Кэшбек'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userservice',
            name='expense',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userservice',
            name='status_cashback',
            field=models.BooleanField(default=1, verbose_name='Статус зачисления кэшбека'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserExpense',
        ),
    ]
