# Generated by Django 3.2.15 on 2024-03-26 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240324_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+79[0-9]{9}$')], verbose_name='Номер телефона'),
        ),
    ]
